# Legal Analytics (LAW3025) - Tutorial 2: 'Data-driven research design'

*Version*: 2023/2024

### 2.1. Understanding data-driven research design

Find an empirical/data-driven legal research article and review the research design by:

1. summarizing the theory underlying the research,
2. describing the main research question(s) and hypothesis(-es),
3. explaining the main finding(s) of the research,
4. evaluating the reliability and validity of their measure(s) and measurement procedure(s), and
5. determining whether the authors disclose any issues of privacy or ethics for their research, and, if not, evaluate that choice.

Form groups of 3 and prepare a presentation covering the five points above in maximum 10 minutes.

A good place to start is to check these publications:

* The International Conference on Artificial Intelligence and Law (ICAIL)
* The International Conference on Legal Knowledge and Information Systems (JURIX)
* The International Workshop on Juris-informatics (JURISIN)
* Journal of Empirical Legal Studies

### 2.2. Python Fundamentals Jupyter Notebook

The following exercises will check your understanding of:

* What are variables in Python.
* How to perform basic calculations.
* How to write functions in Python.
* Read a pandas dataframe.
* How to select columns and rows (subsets) in pandas dataframe.


**Note that programming follows a different approach compared to other disciplines or courses. Programming isn't learned by reading books and expecting to know everything, but rather by putting it into practice. It is a highly iterative learning process. Even the most experienced programmers get stuck all the time and then have to consult the documentation of the used programming libraries (e.g., `pandas`), turn to online communities like `StackOverflow`, or ask `ChatGPT`. When you use such online resources, MAKE SURE THAT YOU UNDERSTAND WHY YOU DO WHAT YOU DO. For example, when using ChatGPT, then ask it to explain the outputs to you. If you don't do this, your learnings from this course will be very limited.**

## Variables and Strings

**1. What is the final value of `position` in the program below?** (Try to predict the value without running the python code, then check your prediction_)

```python
initial = 'Legal'
position = initial
initial = 'Analytics'
```

'Legal' because the variable gets set to the value of the initial variable at that time. It is a pass by value not reference.

**2. If you create and assign to the variable `IDH` the value `= 0.0005`, what happens if you try to get the second digit (e.g. `.`) of `IDH` via index `IDH[1]`?**

I get an error because IDH is a number, not a string and therefore is not indexable, unless you set it to "=0"

In [11]:
IDH = 0.0005
IDH[1]

TypeError: 'float' object is not subscriptable

In [12]:
IDH = "= 0.0005"
IDH[1]

' '

**3. What does the following code print?** Think about it before you write a new python code. Then add some explanation (< 50 words) in text cell.

```python
city_name = 'Arequipa'
print('city_name[1:3] is', city_name[1:3])
```

You will get "city_name[1:3] is re" because the first part is a string and the second one uses the actual variable. Since indices start at 0 we get from the second up to the third character

In [13]:
city_name = 'Arequipa'
print('city_name[1:3] is', city_name[1:3])

city_name[1:3] is re

**4. Can you concatenate strings in python?** Can you demonstrate how with an example in a python cell?

Yes, by simply summing them

In [14]:
first_name = 'Lucas'
middle_name = 'Giovanni'
first_last_name = 'Uberti-Bona'
second_last_name = 'Marin'
first_name + ' ' + middle_name + ' ' + first_last_name + ' ' + second_last_name

'Lucas Giovanni Uberti-Bona Marin'

## Functions

The function syntax should be always as following:

In [15]:
def f(x):
    print(x)

+ **def**   tells Python that you are writing a function _definition_. This line of code is also followed by a colon.

+ **f**     is the name of the function so that the user can call the function later on.

+ **x**     within the parenthesis are parameters passed into the function to be used.

In [16]:
## Suppose we have the following string
x = "I am X"
## We can call our function f on x variable
f(x)

I am X

- Begin the definition of a new function with def.
- Followed by the name of the function.
    - Must obey the same rules as variable names.
- Then parameters in parentheses.
    - Empty parentheses if the function doesnâ€™t take any inputs.
- Then a colon.
- Then an indented block of code.

In [17]:
def print_greeting():
    print('Hello!')

- Defining a function does not run it, it is like assigning a value to a variable. You must call the function to execute the code it contains.

In [18]:
# call the previous function print_greeting
print_greeting()

Hello!

Function can have a return value:
The return value is something that may be retrieved or calculated within the function. For instance:

In [19]:
## Suppose we have a function that multiply 10 to a given integer
def multiplyten(x):
    x = x*10 # In this line, we are assigning a new value to x
    return x # Return is what the function will give back

In [20]:
# now lets call the function mutiplyten
multiplyten(5)

50

### EXERCISE

*Law firms in Netherlands have an hourly rate along with a **x**% office cost and **y**% VAT tax. Write a function to compute the total cost of a law firm for **n** number of hours. The rate per hour of a legal firm in the Hague is â‚¬ 200. In addition to this, they charge 5% office cost and 21% VAT. Use this function to compute the total cost of hiring this law firm for 10 hours.*

In [31]:
def hourly_cost(n:int) -> float:
    cost = n*200*1.05*1.21
    return cost

In [32]:
hourly_cost(10)

2541.0

## Data Handling with Pandas

In [33]:
# Read the data into a dataframe using the url of the csv file
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/maastrichtlawtech/law3025-legal-analytics/main/data/state_crime.csv')
df

,State,Year,Data.Population,Data.Rates.Property.All,Data.Rates.Property.Burglary,Data.Rates.Property.Larceny,Data.Rates.Property.Motor,Data.Rates.Violent.All,Data.Rates.Violent.Assault,Data.Rates.Violent.Murder,...,Data.Rates.Violent.Robbery,Data.Totals.Property.All,Data.Totals.Property.Burglary,Data.Totals.Property.Larceny,Data.Totals.Property.Motor,Data.Totals.Violent.All,Data.Totals.Violent.Assault,Data.Totals.Violent.Murder,Data.Totals.Violent.Rape,Data.Totals.Violent.Robbery
0,Alabama,1960,3266740,1035.4,355.9,592.1,87.3,186.6,138.1,12.4,...,27.5,33823,11626,19344,2853,6097,4512,406,281,898
1,Alabama,1961,3302000,985.5,339.3,569.4,76.8,168.5,128.9,12.9,...,19.1,32541,11205,18801,2535,5564,4255,427,252,630
2,Alabama,1962,3358000,1067.0,349.1,634.5,83.4,157.3,119.0,9.4,...,22.5,35829,11722,21306,2801,5283,3995,316,218,754
3,Alabama,1963,3347000,1150.9,376.9,683.4,90.6,182.7,142.1,10.2,...,24.7,38521,12614,22874,3033,6115,4755,340,192,828
4,Alabama,1964,3407000,1358.7,466.6,784.1,108.0,213.1,163.0,9.3,...,29.1,46290,15898,26713,3679,7260,5555,316,397,992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3110,Wyoming,2015,586107,1902.6,300.6,1500.9,101.0,222.1,179.8,2.7,...,10.1,11151,1762,8797,592,1302,1054,16,173,59
3111,Wyoming,2016,585501,1957.3,302.5,1518.2,136.6,244.2,195.7,3.4,...,10.1,11460,1771,8889,800,1430,1146,20,205,59
3112,Wyoming,2017,579315,1830.4,275.0,1421.0,134.5,237.5,176.4,2.6,...,13.1,10604,1593,8232,779,1376,1022,15,263,76
3113,Wyoming,2018,577737,1785.1,264.0,1375.9,145.2,212.2,150.6,2.3,...,17.3,10313,1525,7949,839,1226,870,13,243,100
3114,Wyoming,2019,578759,1571.1,241.2,1206.7,123.2,217.4,147.6,2.2,...,11.6,9093,1396,6984,713,1258,854,13,324,67

We can get a slice of the data by using the `df.query()` function to select all the records relating to a specific year. For example, by specifying the corresponding column to filter (`Year`) and the desired value (`2007`).

In [34]:
df_2007 = df.query('Year == 2007')
df_2007

,State,Year,Data.Population,Data.Rates.Property.All,Data.Rates.Property.Burglary,Data.Rates.Property.Larceny,Data.Rates.Property.Motor,Data.Rates.Violent.All,Data.Rates.Violent.Assault,Data.Rates.Violent.Murder,...,Data.Rates.Violent.Robbery,Data.Totals.Property.All,Data.Totals.Property.Burglary,Data.Totals.Property.Larceny,Data.Totals.Property.Motor,Data.Totals.Violent.All,Data.Totals.Violent.Assault,Data.Totals.Violent.Murder,Data.Totals.Violent.Rape,Data.Totals.Violent.Robbery
47,Alabama,2007,4627851,3977.7,980.6,2689.5,307.7,448.9,246.7,8.9,...,159.9,184082,45379,124465,14238,20775,11417,412,1548,7398
107,Alaska,2007,683478,3379.2,546.3,2476.9,356.0,661.3,490.3,6.3,...,85.0,23096,3734,16929,2433,4520,3351,43,545,581
167,Arizona,2007,6338755,4532.6,946.4,2793.5,792.6,518.0,318.2,8.6,...,154.0,287308,59988,177076,50244,32835,20170,548,2353,9764
227,Arkansas,2007,2834797,3955.5,1130.1,2578.5,246.9,537.1,374.9,7.0,...,109.5,112130,32035,73096,6999,15226,10629,198,1294,3105
287,California,2007,36553215,3043.5,650.7,1790.6,602.2,524.1,299.7,6.2,...,193.4,1112510,237850,654526,220134,191561,109547,2262,9046,70706
347,Colorado,2007,4861515,2999.2,589.0,2067.6,342.6,351.8,234.7,3.2,...,71.2,145808,28633,100519,16656,17101,11410,155,2075,3461
407,Connecticut,2007,3502309,2470.6,446.6,1739.9,284.1,301.1,155.4,3.2,...,122.9,86528,15640,60937,9951,10547,5441,113,690,4303
467,Delaware,2007,864764,3378.5,742.4,2365.3,270.8,705.4,457.6,4.5,...,203.9,29216,6420,20454,2342,6100,3957,39,341,1763
527,District of Columbia,2007,588292,4916.3,667.4,2956.0,1292.9,1415.1,626.7,30.8,...,725.0,28922,3926,17390,7606,8325,3687,181,192,4265
587,Florida,2007,18251243,4088.8,996.3,2689.0,403.4,722.6,473.2,6.6,...,209.1,746249,181836,490783,73630,131878,86372,1202,6149,38155
647,Georgia,2007,9544750,3889.6,946.0,2498.1,445.5,491.5,279.8,7.5,...,181.2,371248,90294,238436,42518,46917,26708,720,2198,17291
707,Hawaii,2007,1283388,4119.3,708.2,2921.5,489.6,276.1,157.5,1.9,...,87.4,52866,9089,37494,6283,3544,2021,24,377,1122
767,Idaho,2007,1499402,2275.8,475.6,1649.1,151.1,256.2,196.2,3.3,...,16.2,34124,7131,24727,2266,3841,2942,49,607,243
827,Illinois,2007,12852548,2935.8,587.6,2084.5,263.7,533.2,315.7,5.9,...,179.7,377322,75524,267911,33887,68528,40573,752,4103,23100
887,Indiana,2007,6345289,3370.8,732.6,2332.4,305.8,335.8,179.3,5.5,...,123.6,213887,46485,147999,19403,21310,11377,350,1738,7845
947,Iowa,2007,2988046,2648.3,574.8,1908.2,165.3,300.2,222.0,1.3,...,44.4,79133,17176,57018,4939,8970,6633,39,970,1328
1007,Kansas,2007,2775997,3709.0,737.1,2662.1,309.8,458.6,335.6,3.8,...,72.8,102961,20461,73900,8600,12730,9315,106,1287,2022
1067,Kentucky,2007,4241474,2546.0,655.9,1685.5,204.6,290.7,157.7,4.9,...,95.9,107987,27820,71489,8678,12329,6690,206,1365,4068
1127,Louisiana,2007,4293204,4204.7,1093.2,2755.3,356.2,740.4,545.5,14.6,...,147.1,180516,46932,118291,15293,31789,23421,625,1427,6316
1187,Maine,2007,1317207,2448.3,512.1,1839.3,96.9,118.8,61.0,1.5,...,26.5,32249,6745,24228,1276,1565,804,20,392,349
1247,Maryland,2007,5618344,3431.5,660.2,2265.9,505.4,641.9,375.1,9.9,...,236.0,192796,37095,127308,28393,36063,21072,554,1179,13258
1307,Massachusetts,2007,6449755,2399.2,554.5,1611.3,233.4,441.7,304.4,2.9,...,108.9,154743,35767,103925,15051,28487,19636,187,1643,7021
1367,Michigan,2007,10071822,3063.5,747.4,1899.2,416.9,533.8,349.0,6.6,...,132.7,308550,75273,191289,41988,53765,35147,661,4592,13365
1427,Minnesota,2007,5197621,3044.8,571.7,2229.7,243.3,289.6,159.6,2.2,...,91.8,158257,29717,115892,12648,15054,8295,116,1873,4770
1487,Mississippi,2007,2918785,3113.9,932.7,1934.8,246.4,291.3,149.8,6.9,...,99.2,90887,27223,56473,7191,8502,4371,202,1033,2896
1547,Missouri,2007,5878415,3829.5,763.8,2659.2,406.5,560.7,392.7,6.2,...,131.5,225113,44897,156319,23897,32962,23082,367,1785,7728
1607,Montana,2007,957861,2906.2,362.9,2329.7,213.6,379.8,314.8,2.8,...,24.3,27837,3476,22315,2046,3638,3015,27,363,233
1667,Nebraska,2007,1774571,3142.4,509.1,2337.7,295.6,311.3,213.5,4.0,...,62.8,55765,9035,41484,5246,5524,3788,71,550,1115
1727,Nevada,2007,2565382,3785.7,971.0,1942.9,871.7,754.9,434.2,7.5,...,270.4,97118,24911,49844,22363,19365,11138,193,1096,6938
1787,New Hampshire,2007,1315828,2005.9,385.6,1513.0,107.2,144.1,81.8,0.9,...,34.3,26394,5074,19909,1411,1896,1076,12,357,451
1847,New Jersey,2007,8685920,2214.4,428.7,1532.9,252.8,328.6,167.7,4.4,...,144.7,192338,37234,133145,21959,28544,14564,381,1032,12567
1907,New Mexico,2007,1969915,3815.8,1057.1,2306.8,451.9,675.7,496.3,9.3,...,117.9,75168,20823,45442,8903,13311,9777,183,1028,2323
1962,New York,2007,19297729,1987.9,336.4,1506.3,145.2,414.4,233.9,4.2,...,161.1,383624,64914,290681,28029,79962,45144,805,2928,31085
2022,North Carolina,2007,9061032,4082.2,1199.6,2574.1,308.5,466.1,283.9,6.4,...,149.4,369893,108700,233241,27952,42231,25727,584,2386,13534
2082,North Dakota,2007,639715,2000.3,361.7,1485.0,153.5,209.9,156.2,2.7,...,11.7,12796,2314,9500,982,1343,999,17,252,75
2142,Ohio,2007,11466917,3468.1,863.8,2308.2,296.1,355.4,150.2,4.6,...,160.0,397681,99049,264677,33955,40759,17218,529,4661,18351
2202,Oklahoma,2007,3617316,3558.3,950.1,2232.2,376.0,504.1,360.8,6.2,...,93.8,128714,34367,80747,13600,18234,13053,224,1565,3392
2262,Oregon,2007,3747455,3543.0,613.2,2539.2,390.6,293.9,181.4,2.0,...,76.4,132773,22979,95157,14637,11015,6799,76,1276,2864
2322,Pennsylvania,2007,12432792,2363.5,451.2,1699.1,213.2,416.7,226.8,5.8,...,156.4,293850,56091,211248,26511,51806,28198,725,3443,19440
2382,Rhode Island,2007,1057832,2606.8,492.1,1812.7,302.0,229.1,131.1,1.8,...,71.8,27576,5206,19175,3195,2424,1387,19,258,760
2442,South Carolina,2007,4407709,4294.8,1030.0,2876.8,388.0,785.7,593.0,8.3,...,144.2,189304,45398,126802,17104,34630,26139,364,1773,6354
2502,South Dakota,2007,796214,1736.8,332.4,1305.9,98.5,241.9,168.8,3.9,...,14.8,13829,2647,10398,784,1926,1344,31,433,118
2562,Tennessee,2007,6156719,4098.6,1004.1,2741.8,352.8,755.0,533.4,6.6,...,179.2,252342,61817,168807,21718,46482,32843,405,2201,11033
2622,Texas,2007,23904380,4122.3,955.1,2774.0,393.2,510.4,306.9,5.9,...,162.2,985421,228320,663101,94000,122014,73357,1419,8460,38778
2682,United States,2007,301621157,3276.4,726.1,2185.4,364.9,471.8,287.2,5.7,...,148.3,9882212,2190198,6591542,1100472,1422970,866358,17128,92160,447324
2742,Utah,2007,2645330,3518.7,589.5,2592.2,337.0,239.9,148.5,2.2,...,53.9,93082,15594,68573,8915,6347,3928,59,935,1425
2802,Vermont,2007,621254,2366.5,515.1,1747.0,104.5,129.1,93.7,2.1,...,12.7,14702,3200,10853,649,802,582,13,128,79
2862,Virginia,2007,7712091,2486.5,415.3,1888.4,182.8,272.8,144.3,5.4,...,99.8,191763,32028,145634,14101,21035,11131,415,1793,7696
2922,Washington,2007,6468424,4047.0,817.4,2640.2,589.3,336.5,198.8,2.7,...,94.0,261776,52874,170782,38120,21768,12862,174,2653,6079
2982,West Virginia,2007,1812035,2517.6,597.2,1728.5,191.9,276.8,205.1,3.6,...,46.7,45620,10822,31321,3477,5016,3716,65,388,847
3042,Wisconsin,2007,5601640,2843.9,497.9,2105.8,240.3,291.5,168.5,3.3,...,97.8,159305,27890,117957,13458,16330,9438,185,1227,5480
3102,Wyoming,2007,522830,2879.1,452.3,2271.3,155.5,257.1,204.1,4.0,...,16.1,15053,2365,11875,813,1344,1067,21,172,84

Similarly, we can find various crime records for the state of Wisconsin for the year 2007 by doing the following operation.

In [35]:
df_2007_wisconsin = df_2007.query('State == "Wisconsin" ')
df_2007_wisconsin

,State,Year,Data.Population,Data.Rates.Property.All,Data.Rates.Property.Burglary,Data.Rates.Property.Larceny,Data.Rates.Property.Motor,Data.Rates.Violent.All,Data.Rates.Violent.Assault,Data.Rates.Violent.Murder,...,Data.Rates.Violent.Robbery,Data.Totals.Property.All,Data.Totals.Property.Burglary,Data.Totals.Property.Larceny,Data.Totals.Property.Motor,Data.Totals.Violent.All,Data.Totals.Violent.Assault,Data.Totals.Violent.Murder,Data.Totals.Violent.Rape,Data.Totals.Violent.Robbery
3042,Wisconsin,2007,5601640,2843.9,497.9,2105.8,240.3,291.5,168.5,3.3,...,97.8,159305,27890,117957,13458,16330,9438,185,1227,5480

Find all the unique States in the dataframe. Do you find something strange ? Select only the entries from the dataframe which are not states. 

Hint: United States and District of Columbia are not states.

In [36]:
df['State'].unique()

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
       'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Texas', 'United States', 'Utah', 'Vermont', 'Virginia',
       'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'],
      dtype=object)

How would you count the number of unique states in the 'State' column ?

In [16]:
df['State'].nunique()

52

Let's select the 50 States using the query() method. We create a new dataframe, `df_50_States` for this.
Basically, using the & (and) operator we select all the rows in the dataframe which don't belong to 'United States' and 'District of Columbia'.

In [17]:
df_50_States = df.query("State!='United States' & State!='District of Columbia'")
df_50_States

        State  Year  ...  Data.Totals.Violent.Rape  Data.Totals.Violent.Robbery
0     Alabama  1960  ...                       281                          898
1     Alabama  1961  ...                       252                          630
2     Alabama  1962  ...                       218                          754
3     Alabama  1963  ...                       192                          828
4     Alabama  1964  ...                       397                          992
...       ...   ...  ...                       ...                          ...
3110  Wyoming  2015  ...                       173                          125
3111  Wyoming  2016  ...                       205                           59
3112  Wyoming  2017  ...                       263                           76
3113  Wyoming  2018  ...                       243                          100
3114  Wyoming  2019  ...                       324                           67

[2995 rows x 21 columns]

Now let's check how many unique States we have in the `'State'` column.

In [18]:
df_50_States['State']. nunique()

50

### EXERCISE

*Find the total number of robberies (hint: look at data.totals.violent.robbery column) which took place in Rhode Island, Ohio and South Dakota in the year 2015.*

In [44]:
df.query("(State =='Rhode Island' | State == 'Ohio'| State== 'South Dakota') & Year  == 2015")['Data.Totals.Violent.Robbery'].sum()

np.int64(13326)